[2025-03-22T06:34:15.498+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction-facts_generator.generate_txn_fact_data scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T06:34:15.525+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction-facts_generator.generate_txn_fact_data scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T06:34:15.526+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-22T06:34:37.269+0000] {taskinstance.py:1380} INFO - Executing <Task(KafkaProduceOperator): generate_txn_fact_data> on 2025-03-21 00:00:00+00:00
[2025-03-22T06:34:37.291+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2025-03-22T06:34:37.606+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transaction-facts_generator', 'generate_txn_fact_data', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/transaction_facts_generator.py', '--cfg-path', '/tmp/tmpduu9iykt']
[2025-03-22T06:34:37.960+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask generate_txn_fact_data
[2025-03-22T06:35:03.625+0000] {task_command.py:415} INFO - Running <TaskInstance: transaction-facts_generator.generate_txn_fact_data scheduled__2025-03-21T00:00:00+00:00 [running]> on host c601b8b43588
[2025-03-22T06:35:05.226+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kebishaa' AIRFLOW_CTX_DAG_ID='transaction-facts_generator' AIRFLOW_CTX_TASK_ID='generate_txn_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-22T06:35:05.351+0000] {conn.py:385} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.18.0.8', 9092)]>: connecting to kafka_broker:9092 [('172.18.0.8', 9092) IPv4]
[2025-03-22T06:35:07.095+0000] {client_async.py:792} WARNING - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka_broker:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.8', 9092)]> timed out after 1599.9999046325684 ms. Closing connection.
[2025-03-22T06:35:07.096+0000] {conn.py:912} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka_broker:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.8', 9092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 1599.9999046325684 ms
[2025-03-22T06:35:07.103+0000] {conn.py:385} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.18.0.8', 9092)]>: connecting to kafka_broker:9092 [('172.18.0.8', 9092) IPv4]
[2025-03-22T06:35:07.417+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/kafka_operator.py", line 51, in execute
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 406, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1064, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-03-22T06:35:08.528+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transaction-facts_generator, task_id=generate_txn_fact_data, execution_date=20250321T000000, start_date=20250322T063415, end_date=20250322T063508
[2025-03-22T06:35:09.064+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task generate_txn_fact_data (NoBrokersAvailable; 202)
[2025-03-22T06:35:09.124+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-22T06:35:09.198+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
