[2025-03-16T22:01:05.539+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:01:05.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:01:05.562+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:01:05.542+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:01:05.720+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:01:05.624+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:01:05.721+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:01:06.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.589 seconds
[2025-03-16T22:01:36.447+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:01:36.450+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:01:36.452+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:01:36.451+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:01:36.461+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:01:36.459+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:01:36.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:01:36.593+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.154 seconds
[2025-03-16T22:02:06.868+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:02:06.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:02:06.880+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:02:06.878+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:02:06.918+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:02:06.910+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:02:06.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:02:07.011+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.158 seconds
[2025-03-16T22:02:37.325+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:02:37.329+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:02:37.333+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:02:37.332+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:02:37.341+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:02:37.339+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:02:37.342+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:02:37.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.112 seconds
[2025-03-16T22:03:07.758+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:03:07.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:03:07.765+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:03:07.762+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:03:07.776+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:03:07.773+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:03:07.778+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:03:07.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.100 seconds
[2025-03-16T22:03:38.077+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:03:38.080+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:03:38.082+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:03:38.081+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:03:38.099+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:03:38.097+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:03:38.100+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:03:38.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.075 seconds
[2025-03-16T22:04:08.333+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:04:08.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:04:08.339+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:04:08.338+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:04:08.347+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:04:08.345+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:04:08.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:04:08.401+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.075 seconds
[2025-03-16T22:04:38.878+0000] {processor.py:157} INFO - Started process (PID=197) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:04:38.883+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:04:38.889+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:04:38.887+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:04:38.908+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:04:38.904+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:04:38.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:04:39.006+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.141 seconds
[2025-03-16T22:05:09.157+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:05:09.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/branch_dim_generator.py for tasks to queue
[2025-03-16T22:05:09.162+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:05:09.161+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:05:09.171+0000] {logging_mixin.py:151} INFO - [2025-03-16T22:05:09.169+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator.py", line 63
    with DAG(dag_id: 'account_dim_generator',
                   ^
SyntaxError: invalid syntax
[2025-03-16T22:05:09.172+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator.py
[2025-03-16T22:05:09.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/branch_dim_generator.py took 0.071 seconds
